# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 52pojie

on:
  workflow_dispatch:
  schedule:
    - cron: '40 0 * * *'
  watch:
    types: [started]
  repository_dispatch:
    types: 52pojie
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone -b  master https://github.com/SallyU/fuidvsfjkd.git ~/scripts
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
      - name: '运行 【52签到】'
        run: |
          cd ~/scripts
          node 52pojie.js
        env:
          WAPJ: ${{ secrets.WAPJ }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
